### PR TITLE
Resolve cohere model error from Sentry

### LINKED ISSUE #38: ValidationException: Malformed input request: #/texts/0: expected maxLength: 2048, actual: 2918#/texts/1: expected max...
Sentry Issue: [MEMOIRE-5](https://ansearch.sentry.io/issues/6062448658/?referrer=github_integration)

```
ValidationException: Malformed input request: #/texts/0: expected maxLength: 2048, actual: 2918#/texts/1: expected maxLength: 2048, actual: 2917#/texts/2: expected maxLength: 2048, actual: 2913#/texts/3: expected maxLength: 2048, actual: 2930#/texts/4: expected maxLength...
  File "/memoire/src/ai/embedding/model/ai-embedding-model-cohere.ts", line 87, in pe
  File "/memoire/src/ai/embedding/model/ai-embedding-model-cohere.ts", line 111, in yt
  File "/memoire/src/ai/embedding/ai-embeddings-interface.ts", line 43, in ve
  File "/memoire/src/core/core-search.ts", line 60, in qe
  File "/memoire/src/api/search/api-search-routes.ts", line 145, in Object.?
...
(7 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by sriram-vinnakota**
Hi,

The error in #38 is regarding character limit to cohere embedding v3 model, token limit also still applicable.

The charecter limit is the estimate they provided for 512 tokes is 2048 characters. 

so I have added the character limit on top of token limit.

close #38

### CODE REVIEW

File: src/ai/embedding/model/tests/integration/test-variables.ts
Comment (Mael-Abgrall) [inline src/ai/embedding/model/tests/integration/test-variables.ts:1]: a few tips:

- Good use of a string to verify the chunking result is consistent
- Leverage this! It means you have direct view of the generated chunks, tweak your result, so the function would generate the same result
- Be careful about naming, this chunking is not reserved to cohere, but ought to work with any model; replace cohereChunks by expectedChunks

File: src/ai/embedding/model/index.ts
Comment (Mael-Abgrall) [inline src/ai/embedding/model/index.ts:1]: You got a good grasp of how and why the index exists

however I think in this case it's not needed to have a chunking method for each individual models (remember, simplicity!)

File: src/ai/embedding/model/tests/integration/ai-embedding-model-cohere-integration.test.ts
Comment (Mael-Abgrall) [inline src/ai/embedding/model/tests/integration/ai-embedding-model-cohere-integration.test.ts:1]: good

**Review by Mael-Abgrall — CHANGES_REQUESTED** [review]
too complicated, you have good ideas, but remember more code = more complexity = harder to maintain.

Additionally, I think this is the perfect time to move away from langchain (this library is taking a lot of space, because it bundles absolutely everything, which is bad)

This means creating our own token splitting algorithms, which is nice because it ALSO help understand and go step by step towards smarter chunking (aka we do length based first, then try text structures, semantic and only at the end agentic chunking)

I would suggest this file structure:
```bash
- src/ai/embedding
    | ai-embeddings-interface.ts
    |
    |- models/
    |    | model-a.ts
    |    | model-b.ts
    |
    |- chunking/
    |    | index.ts
    |    | ai-embeddings-chunking-length.ts
    |    | ai-embeddings-chunking-text-structure.ts
    |    | ai-embeddings-chunking-semantic.ts
```

**Focus only on the length-based one!**

here is an algorithm that could help (test it!):

```pseudo
chunks = []
basicSplit = myString.split('\n)
currentChunkBuffer: string

for iteration; iteration < basicSplit.length
  if (basicSplit[iteration] + currentChunkBuffer).length >= 2048:
    chunks.push(basicSplit[iteration] + currentChunkBuffer)

  else:
      currentChunkBuffer = currentChunkBuffer + basicSplit[iteration]

chunks.push(currentChunkBuffer)
return chunks
```

File: src/ai/embedding/chunking/ai-chunking-fixed-size.ts [hunk 1]
```diff
@@ -0,0 +1,41 @@
...
+  separator?: string;
+  tokenLimit?: number;
+}): string[] {
+  const chunks: string[] = [];
+  const baseSplit = document.split(separator);
+  const encoding = get_encoding('cl100k_base');
+  let currentChunkBuffer = '';
+  for (const baseChunk of baseSplit) {
+    if (
+      (currentChunkBuffer + baseChunk).length <= 2048 &&
```
Comment (Mael-Abgrall) [inline src/ai/embedding/chunking/ai-chunking-fixed-size.ts:27]: if you are using variables to set the maximum limit, either use variables for both, or don't

consistency is important ;)

File: src/ai/embedding/chunking/ai-chunking-fixed-size.ts [hunk 2]
```diff
@@ -0,0 +1,41 @@
...
+      encoding.encode(currentChunkBuffer + baseChunk).length <= tokenLimit
```
Comment (Mael-Abgrall) [inline src/ai/embedding/chunking/ai-chunking-fixed-size.ts:28]: the encoder needs to be freed

I'd suggest to adapt this code this way:

```typescript
const charLength = (currentChunkBuffer + baseChunk).length;
const tokensLength = encoding.encode(currentChunkBuffer + baseChunk).length;
encoding.free();
if (
  charLength <= maxChar &&
  tokensLength <= maxTokens
) {
  // ...
}
```

File: src/ai/embedding/chunking/ai-chunking-fixed-size.ts [hunk 3]
```diff
@@ -0,0 +1,41 @@
...
+ * Split a document into chunks based on fixed size of charecter and tokens
+ * @param root named parameters
+ * @param root.document the document to split into chunks
+ * @param root.separator a string such as \n or ' ' to seperate the chunk, default ' '
+ * @param root.tokenLimit maximum token length of the chunk, default 512
+ * @returns a list of chunks
+ */
+export function createLengthBasedChunks({
+  document,
+  separator = ' ',
```
Comment (Mael-Abgrall) [inline src/ai/embedding/chunking/ai-chunking-fixed-size.ts:14]: I need a comment here, (no need elsewhere) about why you chose the space as default.

It seems models now can handle \n or [space] fine

again, just a way to document stuff

additionally, if you think that the only separators needed are space or \n, you can specify this in typescript, to improve dev experience:

```ts
separator?: ' ' | '\n';
```

File: src/ai/embedding/chunking/ai-chunking-fixed-size.ts [hunk 4]
```diff
@@ -0,0 +1,41 @@
...
+      (currentChunkBuffer + baseChunk).length <= 2048 &&
+      encoding.encode(currentChunkBuffer + baseChunk).length <= tokenLimit
+    ) {
+      currentChunkBuffer += baseChunk + separator;
+    } else {
+      chunks.push(currentChunkBuffer);
+      currentChunkBuffer = baseChunk + separator;
+    }
+  }
+  if (currentChunkBuffer) {
```
Comment (Mael-Abgrall) [inline src/ai/embedding/chunking/ai-chunking-fixed-size.ts:36]: `if` is not needed, either the buffer is empty `''` or the buffer has a string

this reduce complexity in your code

File: src/ai/embedding/chunking/tests/integration/ai-chuncking-fixed-size-integration.test.ts [hunk 5]
```diff
@@ -0,0 +1,19 @@
...
+    expect(chunks.length).toBe(testLengthBasedChunks.length);
+    expect(chunks).toStrictEqual(testLengthBasedChunks);
+  });
+  test('Chunking a small text should still return chunks', async () => {
+    const miniText = 'return this as a list of one ele';
+    const chunks = createLengthBasedChunks({
+      document: miniText,
+    });
+    expect(chunks.length).toBe(1);
+    expect(chunks).toStrictEqual([miniText + ' ']);
```
Comment (Mael-Abgrall) [inline src/ai/embedding/chunking/tests/integration/ai-chuncking-fixed-size-integration.test.ts:17]: Interesting, another overlook of this algorithm I made!

js has a builtin function to trim spaces (eg: `   my string   `.trim() -> `my string`)
[MDN doc](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/trim)

what you can do, it an additional test with a single chunk, to verify extra spaces are trimmed

eg:

```ts
// test buffers are trimmed
const myString = "     my string     ";
expect(output).toStrictEqual(['my string']);
const myLongString= "                                  my string 1                 my string 2" // make this string 2048 characters
expect(output).toEqual(['my string 1\nmy string 2']); // this will also make you test the '\n' as a splitter
```

**Review by Mael-Abgrall — CHANGES_REQUESTED** [review]
Good work, a few comments to make your code more stable
